import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.postgresql:postgresql:42.2.27.jre7")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.testcontainers:testcontainers:1.17.6")
}

group = "net.bitnine"
version = "1.4.2"
description = "Agensgraph JDBC"
java.sourceCompatibility = JavaVersion.VERSION_1_7

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<Jar> {
    destinationDirectory.set(file("$rootDir/dist"))
}

tasks.withType<ShadowJar> {
    relocate(
        "org.json.simple",
        "net.bitnine.agensgraph.deps.org.json.simple"
    )
    relocate(
        "org.postgresql",
        "net.bitnine.agensgraph.deps.org.postgresql"
    )
    dependencies {
        exclude(dependency("junit:junit"))
        exclude(dependency("org.testcontainers:testcontainers"))
        exclude(dependency("org.hamcrest:hamcrest-core"))
    }
}
